# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d970333fd4e438ef8607b0c195d83c6ae7b123a07e4c0d3bc47cf36ace053fe2e74f8bc12840df136c07d37b0d03414d1728de465124158af8c7ed7eca9b67

test:
  secret_key_base: 75d7af1184cc8630894ad29a3f62f8380e8639c1c6ade290b47eb4dcb0e244375648a9429be8047222ab629c5ba696e3916fe1311f9d67904e204a959af2f1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
